version: '2.4'
services:
    drone-1:
        hostname: obu-1
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=1
            - VANETZA_STATION_TYPE=255
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:01
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        volumes:
            - ./tools/socktap/config.ini:/config.ini
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.10
        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    drone-2:
        hostname: obu-2
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=2
            - VANETZA_STATION_TYPE=255
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:02
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        volumes:
            - ./tools/socktap/config.ini:/config.ini
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.20

        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    drone-3:
        hostname: obu-3
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=3
            - VANETZA_STATION_TYPE=255
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:03
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        volumes:
            - ./tools/socktap/config.ini:/config.ini
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.30

        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    drone-4:
        hostname: obu-4
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=4
            - VANETZA_STATION_TYPE=255
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:04
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        volumes:
            - ./tools/socktap/config.ini:/config.ini
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.40

        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536

    drone-5:
        hostname: obu-5
        restart: always
        image: code.nap.av.it.pt:5050/mobility-networks/vanetza:latest
        cap_add:
            - "NET_ADMIN"
        environment:
            - VANETZA_STATION_ID=5
            - VANETZA_STATION_TYPE=255
            - VANETZA_MAC_ADDRESS=6e:06:e0:03:00:05
            - VANETZA_INTERFACE=br0
            - START_EMBEDDED_MOSQUITTO=true
            - SUPPORT_MAC_BLOCKING=true
        volumes:
            - ./tools/socktap/config.ini:/config.ini
        networks:
            vanetzalan0:
                ipv4_address: 192.168.98.50

        sysctls:      
            kernel.msgmax:  65536
            kernel.msgmnb:  65536
            
networks:
  vanetzalan0:
    external: true